name: v_chat_voice_player
description: v chat voice player package this item is part of v_chat_sdk and it can be used as a standalone package
version: 2.0.0
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/v-chat-sdk/v_chat_voice_player/issues 
repository: https://github.com/v-chat-sdk/v_chat_voice_player

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  meta: ^1.12.0
  path: ^1.8.3
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.38
  v_platform: ^1.2.3
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
platforms:
  android:
  ios:
  web:
  windows:
  macos:
