name: v_chat_voice_player
description: v chat voice player package this item is part of v_chat_sdk and it can be used as a standalone package
version: 1.2.1
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/v-chat-sdk/v_chat_voice_player/issues 
repository: https://github.com/v-chat-sdk/v_chat_voice_player

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  meta: ^1.9.1
  path: ^1.8.3
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.34
  v_platform: ^1.2.1
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
platforms:
  android:
  ios:
  web:
  windows:
  macos:
