name: voice_example
version: 1.0.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_cache_manager: ^3.3.2
  sizer: ^2.0.15
  v_platform: ^1.2.3
  v_chat_voice_player:
    path: ../
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true

